import Head from 'next/head';

import { Inter } from 'next/font/google';
import { useRouter } from 'next/router';

import useTranslation from 'next-translate/useTranslation';
import { useQuery } from '@tanstack/react-query';
import HomeService from '@/services/HomeService';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { locale } = useRouter();
  const { t } = useTranslation();
  let newsCount = 5;
  const { data, isLoading, error } = useQuery<any>({
    queryKey: ['fetch-home-news', newsCount, locale],
    queryFn: () => HomeService.getHomeNews(locale, newsCount),
  });

  console.log('first', data);

  return (
    <>
      <Head>
        <title>KSGAAL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="alternate"
          hrefLang={locale === 'ar' ? 'ar-EG' : 'en-US'}
          href="/"
        />
      </Head>
      <h2>{t('common:hello')}</h2>
    </>
  );
}
